#!/usr/bin/env bash
# Build a developer-only CV Desk.app (repo + venv wrapper — not redistributable).
# Paths are resolved at launch relative to this .app so moving the whole cv_desk tree works.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIST="$ROOT/dist"
APP="$DIST/CV Desk.app"
MACOS="$APP/Contents/MacOS"
RES="$APP/Contents/Resources"

mkdir -p "$MACOS" "$RES"

# Prefer local .venv; fall back to parent monorepo .venv (resolved at launch, not bake-time).
cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleExecutable</key>
  <string>CVDesk</string>
  <key>CFBundleIdentifier</key>
  <string>com.bocchisad.cvdesk</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>CV Desk</string>
  <key>CFBundleDisplayName</key>
  <string>CV Desk</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>1.0.2</string>
  <key>CFBundleVersion</key>
  <string>1.0.2</string>
  <key>LSMinimumSystemVersion</key>
  <string>13.0</string>
  <key>LSUIElement</key>
  <true/>
  <key>NSHighResolutionCapable</key>
  <true/>
  <key>NSCameraUsageDescription</key>
  <string>CV Desk uses the camera for hand-gesture desk controls.</string>
</dict>
</plist>
PLIST

cat > "$MACOS/CVDesk" <<'EOF'
#!/bin/bash
# Generated by scripts/build_app.sh — do not edit; rebuild instead.
# DEV-ONLY: resolves repo as ../../.. from Contents/MacOS (…/cv_desk/dist/CV Desk.app/…).
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
APP_BUNDLE="$(cd "$HERE/../.." && pwd)"
ROOT="$(cd "$APP_BUNDLE/../.." && pwd)"

if [[ -x "$ROOT/.venv/bin/python" ]]; then
  VENV_PY="$ROOT/.venv/bin/python"
elif [[ -x "$ROOT/../.venv/bin/python" ]]; then
  VENV_PY="$(cd "$ROOT/.." && pwd)/.venv/bin/python"
else
  echo "CV Desk: no venv at $ROOT/.venv or $ROOT/../.venv" >&2
  echo "  cd \"$ROOT\" && python3 -m venv .venv && .venv/bin/pip install -r requirements.txt" >&2
  exit 1
fi

export PYTHONPATH="$ROOT"
export CVDESK_APP_BUNDLE="$APP_BUNDLE"
cd "$ROOT"
exec "$VENV_PY" -m cv_desk "$@"
EOF
chmod +x "$MACOS/CVDesk"
# Force Unix line endings (editors / tools may inject CR).
python3 - "$MACOS/CVDesk" <<'PY'
import pathlib, sys
p = pathlib.Path(sys.argv[1])
p.write_bytes(p.read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n"))
p.chmod(0o755)
PY

cat > "$RES/README.txt" <<EOF
CV Desk menu-bar app (developer wrapper).
Built $(date -u +%Y-%m-%dT%H:%MZ)

This .app is NOT redistributable: it runs python from a nearby .venv and
the cv_desk source tree. Permissions (Camera / Accessibility / Screen
Recording) usually attach to the Python binary, not "CV Desk".
EOF

echo "built: $APP  (dev-only wrapper)"
echo "  run:  open \"$APP\""
echo "  or:   \"$MACOS/CVDesk\""
