#!/usr/bin/env bash
# Build a developer-friendly CV Desk.app that points at this repo + venv.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIST="$ROOT/dist"
APP="$DIST/CV Desk.app"
MACOS="$APP/Contents/MacOS"
RES="$APP/Contents/Resources"

if [[ -x "$ROOT/.venv/bin/python" ]]; then
  VENV_PY="$ROOT/.venv/bin/python"
elif [[ -x "$ROOT/../.venv/bin/python" ]]; then
  VENV_PY="$(cd "$ROOT/.." && pwd)/.venv/bin/python"
else
  echo "error: no venv found at $ROOT/.venv or $ROOT/../.venv" >&2
  echo "  create one and: pip install -r requirements.txt" >&2
  exit 1
fi

mkdir -p "$MACOS" "$RES"

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleExecutable</key>
  <string>CVDesk</string>
  <key>CFBundleIdentifier</key>
  <string>com.bocchisad.cvdesk</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>CV Desk</string>
  <key>CFBundleDisplayName</key>
  <string>CV Desk</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>0.1.0</string>
  <key>CFBundleVersion</key>
  <string>0.1.0</string>
  <key>LSMinimumSystemVersion</key>
  <string>13.0</string>
  <key>LSUIElement</key>
  <true/>
  <key>NSHighResolutionCapable</key>
  <true/>
  <key>NSCameraUsageDescription</key>
  <string>CV Desk uses the camera for hand-gesture desk controls.</string>
</dict>
</plist>
PLIST

cat > "$MACOS/CVDesk" <<EOF
#!/bin/bash
# Generated by scripts/build_app.sh — do not edit; rebuild instead.
set -euo pipefail
ROOT="$ROOT"
VENV_PY="$VENV_PY"
export PYTHONPATH="\$ROOT"
export CVDESK_APP_BUNDLE="\$(cd "\$(dirname "\$0")/../.." && pwd)"
cd "\$ROOT"
exec "\$VENV_PY" -m cv_desk "\$@"
EOF
chmod +x "$MACOS/CVDesk"
# Force Unix line endings (editors / tools may inject CR).
python3 - "$MACOS/CVDesk" <<'PY'
import pathlib, sys
p = pathlib.Path(sys.argv[1])
p.write_bytes(p.read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n"))
p.chmod(0o755)
PY

# Tiny placeholder icon note (optional icns later)
echo "CV Desk menu-bar app. Built $(date -u +%Y-%m-%dT%H:%MZ)" > "$RES/README.txt"

echo "built: $APP"
echo "  python: $VENV_PY"
echo "  run:    open \"$APP\""
echo "  or:     \"$MACOS/CVDesk\""
